
language: java
branches:
  only:
  - develop
  - /^release-[0-999].[0-999]$/
  - master
notifications:
  email:
    recipients:
    - j.garceran@alumnos.upm.es

addons:
  sonarcloud:
    organization: "jesusgarce" # the key of the org you chose at step #3
    token:
      secure: "*********" # encrypted value of your token
script:
# the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
- mvn clean verify sonar:sonar -Dsonar.projectKey=iwvg-ecosystem-jesus-garceran